# Generated by Django 4.2.10 on 2024-02-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="in_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
